### ISSUE TITLE
scams not allowed.

### ISSUE THREAD

**Issue by adelsika** [Pr0x13/iDict#63]
i need the password for my icloud account

**Comment by diabloCcashgetter** [comment]
Yes dm me

**Comment by diabloCcashgetter** [comment]
I have a software

**Comment by adelsika** [comment]
Ok great so do I need to send you the iCloud email or what do you need 

Adel Sika 
Owner
www.sikastables.com
FB/SikaStud
Phone : +201222178187
Email: ***@***.***
Address : 3 Gesr El Suez Street - Infront of El Shams Club







CONFIDENTIALITY NOTE:
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by steyndwickus** [comment]
Hi 27677306078

**Comment by adelsika** [comment]
What Info do you need from me 

Adel Sika 
Owner
www.sikastables.com
FB/SikaStud
Phone : +201222178187
Email: ***@***.***
Address : 3 Gesr El Suez Street - Infront of El Shams Club







CONFIDENTIALITY NOTE:
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by diabloCcashgetter** [comment]
So I’m a need the iCloud email $400 and 12 -16 houes

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by steyndwickus** [comment]
Hello yes I'll be needing the email that you want unlock an the serial
number on the phone.   Then you can deposit $400 into my PayPal account..
use your serial number as reference

This take 2-3 days

Ps: plz don't bother me with millions of unnecessary questions this the
procedure take or leave it ..

My email is ***@***.***
Thank you

**Comment by diabloCcashgetter** [comment]
Yo this nigga bro I’ll beat his price and like I said 12 to 16 hours not days dm my email diablo9opps@hotmail.com

**Comment by adelsika** [comment]
How much and how do you guarantee that after I pay you will provide me with the service 

Adel Sika 
Owner
www.sikastables.com
FB/SikaStud
Phone : +201222178187
Email: ***@***.***
Address : 3 Gesr El Suez Street - Infront of El Shams Club







CONFIDENTIALITY NOTE:
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by diabloCcashgetter** [comment]
I’ll beat his price 50 bucks lower so $350 and this is my life I just spent
250000 dollars on the computers and building this software

**Comment by diabloCcashgetter** [comment]
I also need your permission written permission that is that you are
allowing me to remote control your computer so I can do it from my house

**Comment by adelsika** [comment]
And if the job is not done or if you were not able to get me the passenger for the iCloud email I want . How do I get my money back .  I can pay half the amount before the job is done then after it’s done I pay the remaining. How do you receive payments . PayPal or how do I pay you 

Adel Sika 
Owner
www.sikastables.com
FB/SikaStud
Phone : +201222178187
Email: ***@***.***
Address : 3 Gesr El Suez Street - Infront of El Shams Club







CONFIDENTIALITY NOTE:
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by steyndwickus** [comment]
If it's open it's open . Just be careful af how many scamers there is now .

**Comment by adelsika** [comment]
Why do you want to remote control my computer. I thought you can do it without having access to my computer 

Adel Sika 
Owner
www.sikastables.com
FB/SikaStud
Phone : +201222178187
Email: ***@***.***
Address : 3 Gesr El Suez Street - Infront of El Shams Club







CONFIDENTIALITY NOTE:
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.

**Comment by diabloCcashgetter** [comment]
We don't have to do remote control the other option is that you have to just be all night whenever i need you to press a couple of buttons it's not necessary that we remove control at all i just did would be

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by adelsika** [comment]
Ya but the email I want the password for is not on my computer so why do we need my computer 

Adel Sika 
Owner
www.sikastables.com
FB/SikaStud
Phone : +201222178187
Email: ***@***.***
Address : 3 Gesr El Suez Street - Infront of El Shams Club







CONFIDENTIALITY NOTE:
The contents of this e-mail message and any attachments are confidential and are intended solely for addressee. The information may also be legally privileged. This transmission is sent in trust, for the sole purpose of delivery to the intended recipient. If you have received this transmission in error, any use, reproduction or dissemination of this transmission is strictly prohibited. If you are not the intended recipient, please immediately notify the sender by reply e-mail or phone and delete this message and its attachments, if any.
